# Generated by Django 3.0.6 on 2020-05-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='CommentUser',
        ),
    ]
